#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

rsync -avh --progress ~/.config/kitty/ $SCRIPT_DIR/kitty

git add .
git commit -m "sync n' push"
git push