#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

rsync -avh --progress ~/.config/kitty           $SCRIPT_DIR/kitty
rsync -avh --progress ~/.config/fish            $SCRIPT_DIR/fish
rsync -avh --progress ~/.config/starship.toml   $SCRIPT_DIR/starship/

git add .
git commit -m "sync n' push"
git push