#!/usr/bin/env bash
# Source ends with / → copy contents of the folder into destination
# Source without / → copy the folder itself into destination

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

rsync -avh --progress --delete ~/.config/kitty/ $SCRIPT_DIR/kitty/
rsync -avh --progress --delete ~/.config/fish/ $SCRIPT_DIR/fish/
rsync -avh --progress --delete ~/.config/starship.toml $SCRIPT_DIR/starship/

# git add .
# git commit -m "sync n' push"
# git push
