#!/usr/bin/env bash
# Source ends with / → copy contents of the folder into destination
# Source without / → copy the folder itself into destination
set -u

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

rsync -avh --progress --delete "$HOME/.config/kitty/" "$SCRIPT_DIR/kitty/"
rsync -avh --progress --delete "$HOME/.config/fish/" "$SCRIPT_DIR/fish/"
rsync -avh --progress --delete "$HOME/.config/starship.toml" "$SCRIPT_DIR/starship/starship.toml"

# git add .
# git commit -m "sync n' push"
# git push
